
CREATE TABLE USERS
( FName		VARCHAR(10)		NOT NULL, 
  Minit     CHAR,
  Lname     VARCHAR(20)     NOT NULL,
  Username  VARCHAR(20)		NOT NULL,
  Password  VARCHAR(20)		NOT NULL,
  UserID	INT	AUTO_INCREMENT	NOT NULL,
  
PRIMARY KEY		(UserID));

CREATE TABLE JOB_LISTING (
  JobID      INT AUTO_INCREMENT,
  CName      VARCHAR(15) NOT NULL,
  JTitle     VARCHAR(20) NOT NULL,
  Location   VARCHAR(20) NOT NULL,
  Salary     INT NOT NULL,
  C_Email    VARCHAR(50),
  C_Phone    BIGINT,
  Job_Desc   TEXT,
  Date_App   DATE NOT NULL,
  App_Status VARCHAR(15) NOT NULL,
  PRIMARY KEY (JobID)
);

CREATE TABLE SPREADSHEET
( id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  Month			VARCHAR(9)		NOT NULL,
  Year			INT				NOT NULL,
  Date_Created	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Modified_T	TIME,
  Modified_D	DATE,
  
  FOREIGN KEY (user_id) REFERENCES users(UserID));
  
  
  
