
CREATE TABLE USERS
( Username  VARCHAR(20)		NOT NULL,
  Password  VARCHAR(20)		NOT NULL,
  UserID	INT	AUTO_INCREMENT	NOT NULL,
  
PRIMARY KEY		(UserID));

CREATE TABLE JOB_LISTING (
  JobID      INT AUTO_INCREMENT,
  Spreadsheet_id INT NOT NULL,
  CName      VARCHAR(50) NOT NULL,
  JTitle     VARCHAR(30) NOT NULL,
  Location   VARCHAR(30) NOT NULL,
  Salary     INT NOT NULL,
  C_Email    VARCHAR(50),
  C_Phone    BIGINT,
  Job_Desc   TEXT,
  Date_App   DATE NOT NULL,
  App_Status VARCHAR(15) NOT NULL,
  PRIMARY KEY (JobID),
  FOREIGN KEY (Spreadsheet_id) REFERENCES SPREADSHEET(id) ON DELETE CASCADE
);

CREATE TABLE SPREADSHEET
( id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Date_Created	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Modified_At DATETIME,
  
  FOREIGN KEY (user_id) REFERENCES users(UserID));
  
  
  
